[site]
# The title of the site
title = "A new site"
# The name of the author
author = "Author Here"

# Site navigation links
# You can remove any navigation links or add more link by adding following lines
#     [[site.nav]]
#     icon = ""
#     link = ""
# Navigation links are added in the order encountered.

[[site.nav]]
icon = "assets/icons/home.svg"
link = "https://example.com"

[[site.nav]]
icon = "assets/icons/instagram.svg"
link = "https://instagram.com/xxx"

[[site.nav]]
icon = "assets/icons/twitter.svg"
link = "https://twitter.com/xxx"

# Lightbox options
[lightbox]
# Show Navitation Arrows
show_arrows  = true
# Show Zoom Icon
show_zoom    = true
# Show Close Icon
show_close   = true
# Show Image Count
show_counter = true

# Setttings for photo size
[image]
# Width for thumbnail images (set either width or height, or both)
thumbnailWidth = 640
# Height for thumbnail images
# thumbnailHeight = 0

# Width for enlarged images (set either width or height, or both)
originalWidth = 2048
# Height for enlarged images
# originalHeight = 0

# Compress Quality (0~100), higher is better.
compressQuality = 75

# Layout for grids
[layout]
minColumn = 1
maxColumn = 4
minWidth = 200

# Photo sections
# You can remove or add more sections by adding following lines
#     [[section]]
#     title = "section title"
#     text = "section description"
#     slug = "section-slug"
#     folder = "folder of photos"
#     ascending = false
# Photo sections are added in the order encountered.
[[section]]
title = "Section 1"
text = ""
slug = "section-1"
folder = "~/photos/section-1"
ascending = false

[[section]]
title = "Section 2"
text = ""
slug = "section-2"
folder = "~/photos/section-2"
ascending = false

# Other setings
[others]
# Folders that should be copied together when exporting sites
folders = [ "assets", "media" ]
# Show `Generated by foto` footer or not
show_foto_footer = true
